### ISSUE TITLE
Add e2e tests for "neuro admin" commands

### ISSUE THREAD

**Issue by anayden** [neuro-inc/platform-client-python#1292]
At the moment, we don't really test `neuro admin` commands because there's no good way to ensure parallels runs of e2e tests don't interfere with each other.

We need a solution to isolate test runs from each other. An idea would be to use a pool of user accounts where account for test run is chosen randomly so that if pool is large enough interference is very unlikely to happen.

**Comment by asvetlov** [comment]
New cluster provisioning by the tests suite run can take an enormous amount of time.
I doubt if this is acceptable.

**Comment by anayden** [comment]
I think this is a valuable thing that we might address in the future. Hence removing the Stale label
