### ISSUE TITLE
Ignore files during neuro-cp at API level

### ISSUE THREAD

**Issue by yartem** [neuro-inc/platform-client-python#1537]
Neuro-extras uses neuro API to upload files:
https://github.com/neuromation/neuro-extras/blob/4aac693896adb1ca9219074cb8b5fbc7381732bf/neuro_extras/main.py#L259

So even though your project has set up `.neuro.toml` to ignore some files during neuro-cp, `neuro-extras image build` won't ignore it and might take a lot of time.

**Comment by yartem** [comment]
In project-0 we do a workaround: copy only necessary folders to a temp directory, cd there, run neuro-extras image build, cd back to the project directory.

**Comment by serhiy-storchaka** [comment]
You can now pass `filter` argument to `download_dir()` and `upload_dir()` and `ignore_file_names` parameter to `upload_dir()`. Is it what you need? Or maybe you have suggestions for changing the API?
