### ISSUE TITLE
Neuro exec stop printing command  output 

### ISSUE THREAD

**Issue by shagren** [neuro-inc/platform-client-python#1717]
#### Description:
Before command like `neuro exec job-name ls -la /` display some output but now display nothing.

Interactive shell work as expected: 
```
neuro exec test sh
<shell inside container here>
```

`-T` option didn't change behavior.

#### Example:
```
neuro run --detach --name test alpine sleep 15m
neuro exec test ls -la /

```
#### Expected behavior:
Files list

#### Additional context:
Tested on:
- Python 3.7.3, Debian 
- Python 3.8.5, Mac

**Comment by serhiy-storchaka** [comment]
I seen one test failed yesterday. The same symptom -- absent output of "exec".
https://github.com/neuromation/platform-client-python/runs/1061953574#step:7:331

This test was passed on all other buildbots so I ignored the failure. But now I can constantly reproduce the issue.
