### ISSUE TITLE
Newlines printed for status if window size is too small

### ISSUE THREAD

**Issue by Shreeyak** [neuro-inc/platform-client-python#1766]
#### Description:
When launching a job, the status is shown, similar to a progress bar, that updates on the same line. However, if the size of the window is too small, it will create a new line for every "tick" of the status untill the size of the window is increased.
In below screenshot, you can see the line `- Status: pending ClusterScalingUp (Scaling up the cluster to get more resources` is printed repeatedly. It only stopped after I increased the width of the window.
For reference, I'm running the command inside `tmux` session in the `terminator` terminal console.
[
![Screenshot from 2020-10-06 17-04-58](https://user-images.githubusercontent.com/12800185/95196947-6ef79280-07f6-11eb-97cc-53c24db2d3a7.png)
](url)

#### Example:
Open a terminator window. Make it small (though the default size should be small enough). Launch a job.

#### Expected behavior:
Even if the size of the window is too small, a new line shouldn't be printed each time status updates.

**Comment by asvetlov** [comment]
The code is rewritten from scratch, please re-check
