### ISSUE TITLE
Feature request: neuro ps --owner=ME

### ISSUE THREAD

**Issue by yartem** [neuro-inc/platform-client-python#1834]
I need to be able to filter out neuro-ps output by myself. Now I need to type `neuro ps -o artemyushkovskiy`, but I need something like `neuro ps -o ME`. This will ease scripting with neuro.

**Comment by asvetlov** [comment]
Is the user "ME" technically allowed by our validators?

**Comment by romasku** [comment]
No, it isn't (from the auth api):
```
def validate_name(value: str) -> Union[str, DataError]:
    # only alphanumeric (lowercase) symbols allowed,
    # hyphens are allowed only surrounded by other symbols,
    # length: from 3 to 255 (inclusively) characters
```
So "ME" is both too short and uses uppercase characters.

**Comment by asvetlov** [comment]
Sounds good then. Are you volunteered to be the issue champion?
Should be an easy PR

**Comment by romasku** [comment]
Yes, I'll do it.
