### ISSUE TITLE
Feature request: `neuro ps --all` to display only a single job with certain job name

### ISSUE THREAD

**Issue by artem-yushkovsky** [neuro-inc/platform-client-python#1835]
**Problem:**
In my experiments, I run multiple jobs with some specific tag, one tag per experiment. Within the experiment. I follow my own job naming convention. Suppose I run the experiment N, some jobs fail, some succeed. I re-run failed jobs, some of them fail, others succeed. I do `neuro ps -a --tag TAG` to see the status of my experiment, and I see the whole history of it, with all failed jobs:

![image](https://user-images.githubusercontent.com/7501517/99157452-ea900d80-26d9-11eb-9405-5df5aa002f15.png)

How do I filter the old failed jobs out?

So I need a way to do `neuro ps -a` and get only jobs with only latest job name I used. Can I do it with means of Unix utilities, or do I have to invole neuro API or ask engineers to enhance neuro CLI to something like: `neuro ps -a --latest` ?

**Comment by asvetlov** [comment]
`--distinct`, similar to SQL?
 Regardless the name, how should the flag work for jobs without names?

**Comment by yartem** [comment]
`--distinct` should work thank you

> how should the flag work for jobs without names

I think, it's better print unnamed jobs than not.
