### ISSUE TITLE
Life span in job status report is "no limit" if job was run with < 1m --life-span

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/platform-client-python#1843]
#### Description:
If you run the job with `--life-span` option and specify any value less than 1 minute, the life-span in the status report will be displayed as "no limit"

#### Example:
1. `neuro run --life-span 50s ubuntu sleep infinity` (job will terminate in time)
2. check `neuro job status <id>` (status is wrong)

#### Expected behavior:
Proper lifespan is displayed, or at least the message "less than a minute", but not "unlimited".

#### Additional context:
Neuro Platform Client 20.11.10

It possibly won't be fixed due to the minor impact, but better to mark it as "known bug".

**Comment by asvetlov** [comment]
Thanks for the report!

The expected behavior is: raise an error if the lifespan is lesser than a minute.
The platform just doesn't support it.

**Comment by romasku** [comment]
Looks like that in this case we send `"max_runtime_minutes": 0` to the platform, and so it kills job just after it starts. So the output is broken, it should show that lifespan is set to 0 minutes. 
Probably it is better to warn user that lifespan is rounded to minutes. Also we can round 1-59 seconds to 1 minute to avoid such problems.
