### ISSUE TITLE
Not clear when --life-span will trigger

### ISSUE THREAD

**Issue by artem-yushkovsky** [neuro-inc/platform-client-python#1860]
I run the job with life-span of 3 hours:
```
$ make jupyter
...
√ The job will die in 3 hours. See --life-span option documentation for details.
```
Then, after 2-3 hours, I would like to check when my job will die:
```
$ n status jupyter-outforz-od
...
Created: 2020-11-20T18:34:57.695750+00:00
Started: 2020-11-20T18:44:59.217128+00:00
```
So it was created at `18:34:57`. The problem is that on my machine it's currently 23:00, which might confuse the user.

Here I propose the following:
1. In `neuro status`, show times in current machine's timezone if possible, or otherwise state explicitly that the UTC-0 was used.
2. In `neuro status`, add explicit timestamp when the life-time will trigger (so that the user doesn't need to search for the field "Life time: 3h", then search for "Started:", and then calculate. `neuro` can do it better.)

**Comment by romasku** [comment]
Re 1:
UTC timezone is already listed there (`+00:00` part). Though using the machine time is a good idea, if we continue to print the corresponding `+HH:MM` part.
Re 2:
Run time limit is a little bit more complicated: it counts only the time when the job is in "RUNNING" state. So for a schedulable job "started + life span" can be incorrect. So I think that this feature is blocked until we parse the complete job history array (issue #1857).

**Comment by romasku** [comment]
Datetime formatting was fixed in https://github.com/neuro-inc/platform-client-python/pull/1995
