### ISSUE TITLE
Neuro-run gets into an infinite ImagePullBackOff loop

### ISSUE THREAD

**Issue by artem-yushkovsky** [neuro-inc/platform-client-python#1871]
When I try to run a job with an image that can't be pulled, my job gets stuck in the loop
```
√ Name: outforz-monitor-20201126-19h26m
- Status: pending Creating
- Status: pending Scheduling
- Status: pending ErrImagePull
- Status: pending ImagePullBackOff
- Status: pending ErrImagePull
- Status: pending ImagePullBackOff
- Status: pending ErrImagePull
- Status: pending ImagePullBackOff
- Status: pending ErrImagePull
- Status: pending ImagePullBackOff ◥ [146.0 sec]^C
...
```
Instead, it should fail on the first `ErrImagePull` error.

Cluster: neuro-compute.

**Comment by yartem** [comment]
Ok so now I encountered the situation where this functionality helped:
```
- Status: pending Creating
- Status: pending Scheduling
- Status: pending ContainerCreating
- Status: pending ErrImagePull
- Status: pending ImagePullBackOff
√ Http URL: https://outforz-run-20201216-16h32m--outforz-bot.jobs.neuro-compute.org.neu.ro
√ The job will die in a day. See --life-span option documentation for details.
√ Status: running          
```
Should we put number of attempts to 3 or 5 after which we consider the image to be missing ?

**Comment by asvetlov** [comment]
Feel free to make a PR please

**Comment by romasku** [comment]
This is controlled by the following code in `platform-api`:
https://github.com/neuro-inc/platform-api/blob/5952a96c34cf6509dd2fa31cc18fb32021d5c4a8/platform_api/config_factory.py#L89-L91

The current default timeout is 2 minutes. Should we change it to 30 seconds, for example?

**Comment by romasku** [comment]
Oh, looks like I see a bug in platform-api code, that leeds to infinite timeout. This happens because `ErrImagePull` and `ImagePullBackOff` are cycling. I'll fix that.

**Comment by romasku** [comment]
The issue that leads to infinite timeout was fixed, and the timeout decreased to 1 minute. Closing this issue.
