### ISSUE TITLE
Error restarting an instance and more

### ISSUE THREAD

**Issue by DSLituiev** [neuro-inc/platform-client-python#1991]
### Description:
I'm following @mariyadavydova's  email instructions 

#### Question
`neuro ls` is producing a piece of void -- that should be it, right?

#### Issues resolved 

1. `git clone git@github.com:pytorch/serve.git` # didn't work for me, I had to use full `git clone https://github.com/pytorch/serve.git`

2. `cp -r` for folders

```
neuro cp serve storage: # fails
[19:09:47] Copying /Users/dlituiev/repos/xcope/torchserve-on-neuro/serve =>
           storage://neuro-compute/dlituiev/serve

ERROR: cannot copy file:///Users/dlituiev/repos/xcope/torchserve-on-neuro/serve to
storage://neuro-compute/dlituiev/serve: [Errno 21] Is a directory, use recursive copy:
'/Users/dlituiev/repos/xcope/torchserve-on-neuro/serve'
neuro cp -r serve storage: # works
```

#### Issues remaining
```
neuro run --name serve --volume storage:serve:/home/serve:rw \
    --preset gpu-small \
    --http 8080 \
    --no-http-auth \
    --detach pytorch/torchserve:0.1.1-cuda10.1-cudnn7-runtime

# Here I left my machine unattended for some 2h, so it might have stopped the instance:

model-server@job-453710eb-27c6-4d7d-b2f9-998195e12095:~$ ERROR: Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x10d8634e0>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/neuromation/lib/python3.7/asyncio/selector_events.py", line 801, in
_read_ready__data_received
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out
ERROR: Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x10d8eb908>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/neuromation/lib/python3.7/asyncio/selector_events.py", line 801, in
_read_ready__data_received
    data = self._sock.recv(self.max_size)
OSError: [Errno 50] Network is down
ERROR: Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x10d96e470>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/neuromation/lib/python3.7/asyncio/selector_events.py", line 801, in
_read_ready__data_received
    data = self._sock.recv(self.max_size)
OSError: [Errno 50] Network is down

neuro exec serve bash                       # this will attach to the instance bash terminal
√ Job ID: job-147c283a-09e5-4e21-a1fe-3af296882dca
√ Name: serve
- Status: pending Creating
√ Http URL: https://serve--dlituiev.jobs.neuro-compute.org.neu.ro
√ The job will die in a day. See --life-span option documentation for details.
√ Status: cancelled
ERROR: Illegal argument(s) (Unexpected exception: Job 'job-147c283a-09e5-4e21-a1fe-3af296882dca' is not
running.. Path with query: /api/v1/jobs/job-147c283a-09e5-4e21-a1fe-3af296882dca/exec_create.)
```

I've restarted it, but ran into another issue:
```
neuro run --name serve --volume storage:serve:/home/serve:rw \
    --preset gpu-small \
    --http 8080 \
    --no-http-auth \
    --detach pytorch/torchserve:0.1.1-cuda10.1-cudnn7-runtime

neuro exec serve bash                       # this will attach to the instance bash terminal
√ Job ID: job-147c283a-09e5-4e21-a1fe-3af296882dca
√ Name: serve
- Status: pending Creating
√ Http URL: https://serve--dlituiev.jobs.neuro-compute.org.neu.ro
√ The job will die in a day. See --life-span option documentation for details.
√ Status: cancelled
ERROR: Illegal argument(s) (Unexpected exception: Job 'job-147c283a-09e5-4e21-a1fe-3af296882dca' is not
running.. Path with query: /api/v1/jobs/job-147c283a-09e5-4e21-a1fe-3af296882dca/exec_create.)

╰─ neuro exec serve bash
ERROR: Illegal argument(s) (Unexpected exception: Job 'job-147c283a-09e5-4e21-a1fe-3af296882dca' is not
running.. Path with query: /api/v1/jobs/job-147c283a-09e5-4e21-a1fe-3af296882dca/exec_create.)
```

**Comment by mariyadavydova** [comment]
> neuro ls is producing a piece of void -- that should be it, right?

Yep, when you initiate a new account on the Neu.ro platform, your storage is empty.

> git clone git@github.com:pytorch/serve.git # didn't work for me, I had to use full git clone https://github.com/pytorch/serve.git

I'm sorry, I used an SSH-based link. It works if you share your RSA key with GitHub.

> cp -r for folders

Oops, my bad, the command should include `-r`, sure.

Regarding the last issue, the problem is that you have used up your GPU quota. I asked for your username to increase it. Now I see it in your logs, so the quota is updated to 100h of GPU. If you restart the last couple of commands, they should work now. I should admit that the error messages are completely misleading, we are working on that.

**Comment by DSLituiev** [comment]
Thank you!

How can I get `Http URL` programmatically?
Let's say I know the job name.

Dima

**Comment by DSLituiev** [comment]
I tried to curl my own model onto the server, but I ran into `curl` and `wget` not found. I tried to `apt get install` -- "not enough permissions" and "`sudo` is not a vaild command".

How do I curl something in?

**Comment by DSLituiev** [comment]
Same for `git`. I tried to run my own torchserve model that I was able to run elsewhere, but I'm getting a "failed to load model" issue from torchserve. Therefore I wanted to re-archive model on the instance, but not able to clone my git repo.

**Comment by mariyadavydova** [comment]
> How can I get Http URL programmatically?

HTTP URL follows a simple pattern: `https://<job-name>--<username>.jobs.neuro-compute.org.neu.ro`, so, for example, when you run those jobs from the guide, it is always `https://serve--dlituiev.jobs.neuro-compute.org.neu.ro` for you.

> How do I curl something in?

Those instructions with curl refer to your local machine. After you have started a serving job, you may go to another terminal window and use CURL from there. Unfortunately, the Docker image those folks from Torch Serve provide doesn't have CURL or anything like that.

> Therefore I wanted to re-archive the model on the instance, but not able to clone my git repo.

In this particular use-case, the most simple solution is to clone the repo on your local machine and upload it to your storage using the `neuro cp -r` command. Say, if you upload it to the same folder which is already mounted to your serving process (`serve` in your case), you won't have to change the serving command anyhow.

**Comment by DSLituiev** [comment]
```
ERROR: Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x10409c940>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle,
bufsize=0>>
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/neuromation/lib/python3.7/asyncio/select
or_events.py", line 801, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out
```

**Comment by YevheniiSemendiak** [comment]
@DSLituiev, thanks for your feedback!

Could you please give us more info, regarding this issue?
We are working on the connection stability of our CLI.

What are the versions of neuro-CLI and neuro-SDK you use?
`pip list | grep neuro`

**Comment by DSLituiev** [comment]
Apologies, I see I posted it w/o steps -- and I forgot where I got it. I must have started posting and pressed "Comment" prematurely, and now I can't find where it was coming from.

Here are my versions:

```
neuro-cli         21.2.19
neuro-sdk         21.2.19
neuromation       20.12.7
```

I've updated it recently, so i

**Comment by YevheniiSemendiak** [comment]
@DSLituiev, sorry for the delayed reply.

In the last update of `neuro-cli` (21.2.19, which you already have), we addressed the connectivity issues on WebSocket transport: in case of some lost heartbeats / lost packages - the transport will be recovered and you will be reattached to the job.
However, if the problem arises on an OS level (network interface reports an error) - it won't help.

So right now, we need to take a closer look at this problem.
Does it reproduce constantly?
Would love to dig deeper, find out what happens and fix that.

Thank you for your feedback and time! 👍
