### ISSUE TITLE
neuro cp -r constantly blinking and jumping

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/platform-client-python#2022]
#### Description:
Bug report from Synthesis.

If you're performing `neuro cp -r` on a directory with a large number of small files, the CLI constantly blinking and "jumping" up and down while copying, making it extremely hard to track the progress.

#### Example:
1. `wget https://raw.githubusercontent.com/neuro-inc/platform-client-python/master/build-tools/garbage-files-generator.py`
2. `python garbage-files-generator.py 10000 1Mb`
3. `neuro storage cp -r data storage:data`

Observe:
- "jumping": how the part with live progress bars constantly changes its size (say, one second you have ~4 lines, next ~20) - it's hard to keep track - appears on Mac OS, Ubuntu terminals, cannot reproduce in neuro job (neuromation/neuro-extras:20.11.20 image).
 
- "blinking": unfortunately, I was not able to reproduce it (neither on my MAC laptop, not on my Ubuntu 16 laptop nor on the neuro job). Maybe @adavydow could give us a hint, what's happening there, or an example to reproduce the problem?

#### Expected behavior:
Re "jumping":  we need to have a view of constant size (a fixed size table), where live copying bars are appearing/disappearing.
Re "blinking": does not happen

#### Additional context:
previously, we discussed this problem in #1163

**Comment by adavydow** [comment]
Showed blinking to @mariyadavydova, will attach the video later (I don't use screen capture software, so will need some time to set it up and I don't have this time today).

**Comment by YevheniiSemendiak** [comment]
Thanks a lot, @adavydow!
