### ISSUE TITLE
Automatically create user's home directory while adding the user to cluster. 

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/platform-client-python#2045]
#### Is your feature request related to a problem? Please describe.
Adding a new user to the cluster implies manual home directory creation (which often might be forgotten to do) -> user cannot properly use his storage.

#### Describe the solution you'd like
When one adds a user to cluster via `neuro admin add-cluster-user CLUSTER_NAME USER_NAME` command, CLI should also create USER_NAME home directory on storage automatically.

**Comment by romasku** [comment]
Users can do `neuro mkdir storage:` themself, but I agree that it is silly.

**Comment by YevheniiSemendiak** [comment]
> Users can do neuro mkdir storage: themself, but I agree that it is silly.
That's it 😄 
Especially when they are becoming puzzled since we forgot to instruct them to do that (either during onboarding or in docs).

**Comment by romasku** [comment]
Fixed on server side
