### ISSUE TITLE
Shared secrets are not listed by `neuro secret ls`

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/platform-client-python#2069]
#### Description:
If you have the access to foreign secrets (shared via direct share, or accessible via some role), they all should be listed in `neuro secret ls` output, similarly to `neuro job ls`.
Currently, only created by you secrets are listed in `neuro secret ls`

#### Example:
1. Given user A and user B (both are regular users within a cluster), user A creates role R and shares his secret with R.
2. User A shares role R with user B OR user A shares secret directly with user B.
3. User B performs `neuro secret ls` and sees only his secrets (while he still able to use the secret, or see it under `neuro acl list`

#### Expected behavior:
3. User B sees the secret in the form `B/secret-name`.

#### Additional context:
Neuro Platform Client 21.3.3

**Comment by romasku** [comment]
This is already implemented, but not deployed to staging https://github.com/neuro-inc/platform-secrets/pull/93. I'll try to deploy it soon.

**Comment by romasku** [comment]
The new version of `platform-secrets` was deployed yesterday. Please recheck and if it works for you, please close an issue.

**Comment by YevheniiSemendiak** [comment]
The secrets are listed, but foreign secrets are not shown in form of a full URI.
Therefore, It is hard to deduce, where's my secret, and where's someone else's.
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/32543098/113422048-c4db7a80-93d4-11eb-86de-66188e04ac64.png">

Neuro Platform Client 21.4.1

**Comment by romasku** [comment]
Good point! I'll work on that, though it will require a server update (at the moment, it doesn't send URI's).
