### ISSUE TITLE
Support filtering & ordering items in `image ls` similar to `job ls`

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/platform-client-python#2094]
#### Is your feature request related to a problem? Please describe.
FR from Synthesis folks.
It would be great to have the ability to filter image listing (same, as `neuro ps` a.k.a. `neuro job ls`) basing on:
- owner;
- name (regex);
- date of creation (need to add this meta info);
- date of modification (tags / reupload);
The next step is to order items, based on those fields.

#### Describe the solution you'd like
That logic is enabled using similar flags, as `job ls` use: `-n/--name PATTERN` for name, `-o/--owner USERNAME`, etc.

#### Describe alternatives you've considered
Currently, we have an alternative ( [Registry Web browser](https://github.com/neuro-actions/registry_browser) ), so the priority isn't high.
However, for CLI-only folks that doesn't work.

**Comment by romasku** [comment]
As our image service supports generic [docker registry API (v2)](https://docs.docker.com/registry/spec/api/), so we a limited to what it supports, and it is limited:
- No support for dates
- No support for filtering

So at the moment, we can only implement client-side owner/name filtering. We might add an additional DB to store images metadata, but it will require a lot of work.

**Comment by YevheniiSemendiak** [comment]
Sounds reasonable, lets have at least owner/name filtering.

**Comment by YevheniiSemendiak** [comment]
done in #2104
