### ISSUE TITLE
`--pass-config` does not properly work

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/platform-client-python#2232]
#### Description:
If you perform `neuro run` with `--pass-config`, the SDK steals the config within the job, but does not set permission bits properly, which breaks the CLI.

#### Example:
1. `neuro run --pass-config python:3.9.6-buster bash`
2. being in job `pip install neuro-cli==21.7.9`
3. being in job `neuro config show`
4. Get an error: `ERROR: Config /root/.neuro has compromised permission bits, run 'chmod 700 /root/.neuro' first`

#### Expected behavior:
SDK sets permission bits and works after `--pass-config`

#### Additional context:
Neuro Platform Client 21.7.9

**Comment by romasku** [comment]
For more than half a year, CLI uses ENV (`NEURO_PASSED_CONFIG`) variable generated on the server-side to "pass config". Config stealing (using files) behavior was preserved for backward compatibility with older CLI inside old images. Maybe this is a good time to drop this completely?

**Comment by YevheniiSemendiak** [comment]
Moreover: if you manually change permission bits to 700, that will cause hang when you're trying to run the job from within the job.
STR:
1. `neuro run --pass-config python:3.9.6-buster bash`
2. being in job `pip install neuro-cli==21.7.9`
3. being in job `mkdir /root.neuro && chmod 700 /root/.neuro`
4. being in job `neuro run --pass-config ubuntu bash`
5. CLI freezes after 
```
root@job-a0272d25-9692-4132-baf5-7ecec973f094:/# neuro run --pass-config ubuntu bash
Temporary config file created on storage: storage://default/yevheniisemendiak/.neuro/b4db4db5-5a7c-4bda-b0b6-b552a97fca74-cfg.
Inside container it will be available at: /var/storage/.neuro/b4db4db5-5a7c-4bda-b0b6-b552a97fca74-cfg.
```

**Comment by YevheniiSemendiak** [comment]
version 21.7.29 fixed the issue
