### ISSUE TITLE
Report `pulling image` in job status

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/platform-client-python#2256]
During the job creation, the job reports `Container creating` status, which implies (1) image download and (2) actual container creation.

This might take up to 5-10 mins, especially if the docker image is quite large ( 5 Gb + ) and depending on the node capabilities.
That confuses the end-user (_why the container is creating for 10 mins? what's wrong with the platform?_)

Could we report those statuses separately and explicitly?
Another solution (yet less user-friendly) - report status "Image pulling and container creating". 

cc @atselousov

**Comment by asvetlov** [comment]
Not sure if the kubernetes provides this information.

**Comment by YevheniiSemendiak** [comment]
I think the only way to get that info is to parse pod events.
The pod status during the image pull is `ContainerCreating`.

**Comment by romasku** [comment]
Fixed by https://github.com/neuro-inc/platform-api/pull/1730
