### ISSUE TITLE
`bucket ls -l` has no header in table and ignores `-q` flag

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/platform-client-python#2392]
#### Example:
1. Import / create a bucket.
2. Upload some files there.
3. Perform `neuro blob ls -lrh --full-uri blob:<bucket-name>`
4. Perofrm `neuro -qq blob ls -lr --full-uri blob:<bucket-name>`

Result:
![image](https://user-images.githubusercontent.com/32543098/138438183-b778ac99-9e1b-4240-98c7-be7b7321d0dc.png)

#### Expected behavior:
3. In this case, the table header should be displayed, smth like `TYPE SIZE DATE(which?) URL`
4. In this case, only the URLs should be displayed, without the table header.

#### Additional context:
Neuro Platform Client 21.9.3

**Comment by romasku** [comment]
`neuro blob ls` mimics Unix `ls` command, the same way `neuro ls` does, therefore it has no header. We even plan to combine them. So, even if we are going to change anything, we should do the same to `neuro ls` to keep internal consistency. Personally, I prefer the way it works currently.

**Comment by asvetlov** [comment]
#2506 adds `-q` mode support.

Regarding the table header, I concur with @romasku
