### ISSUE TITLE
Memory Units Adjustment

### ISSUE THREAD

**Issue by eviltwinhans** [neuro-inc/platform-client-python#2462]
#### Request
The output of memory units to the CLI should be less ambiguous:
- MB instead of M,
- GB instead of G,
- TB instead of T,
- and so on (not sure if we have kB or PB anywhere)...

<img width="877" alt="Screenshot at Dec 06 17-46-29" src="https://user-images.githubusercontent.com/22771839/144867367-045b9b61-23c6-45f9-ac19-6e2e40712226.png">

**Comment by asvetlov** [comment]
The naming follows `ls -lh` convention.
BTW, did you mean TB or TiB?
